### ISSUE TITLE
Sharp rendering - possible?

### ISSUE THREAD

**Issue by octopuserectus** [furious-programming/Fairtris-2-UC#1]
Thanks for this project, I like it a lot. 
It seems that there is some kind of image filtering going on, even in "native" mode. I glanced through the source but wasn't able to figure it out. I find the said filtering very hard on the eyes. 
Would it possible to add an option to disable the said filtering and maybe include an option for integer scaling for fullscreen mode as well? 
It doesn't say anywhere that you're open for feature requests or suggestions, so please feel free to ignore this or close the issue if needed.
Thanks!

**Comment by furious-programming** [comment]
> It seems that there is some kind of image filtering going on, even in "native" mode. I glanced through the source but wasn't able to figure it out.

The sampling algorithm is initialized once, during game initialization, and is set to **linear** to achieve blurry pixels. The option to change the sampling method was intentionally not added to the game because:

1. This version of Fairtris uses rectangular pixels, in line with CRT televisions, so the shape of the image and the sense of speed of the pieces are consistent with Nintendo's original Tetris for the NES console.
2. An image rendered using integer sampling has ugly, sharp, square pixels that look bad and have nothing to do with the retro style.

If you know Free Pascal, you can modify the sources of this game yourself to have square pixels and integer sampling. You can do it neatly, but basically you just need to change three constants and you'll get what you want, regardless of window size and display mode:

1. Change `linear` to `nearest`:
https://github.com/furious-programming/Fairtris-2-UC/blob/077ca5c93efe910958220aa9f5680232b2018249/source/Fairtris.Game.pp#L86
2. Set `1.0` for both of the following constants:
https://github.com/furious-programming/Fairtris-2-UC/blob/077ca5c93efe910958220aa9f5680232b2018249/source/Fairtris.Constants.pp#L44-L46

> Would it possible to add an option to disable the said filtering and maybe include an option for integer scaling for fullscreen mode as well?

Yes, it would be possible, but I created this game for fun and learning (and to play in my free time) and I am not developing it anymore. The sources are open, so if anything happens, there is nothing to stop you from cloning the project and developing it yourself.

The sources are unlicensed (see the [LICENSE](https://github.com/furious-programming/Fairtris-2-UC/blob/master/LICENSE) file for more information), you can do whatever you want with them. ;)
